### ISSUE TITLE
Requires a perl module not shipped with v84

### ISSUE THREAD

**Issue by dreamingkat** [CpanelInc/tech-SSE#39]
Attempted to run this on v84:

[root@mary ~]# /usr/local/cpanel/cpanel -V
84.0 (build 5)

but recieved an error: 

```
[root@mary ~]# /usr/local/cpanel/3rdparty/bin/perl <(curl -s https://raw.githubusercontent.com/cPanelTechs/SSE/master/msp.pl) --auth --limit 5
Can't locate Cpanel/DnsRoots/Resolver.pm in @INC (you may need to install the Cpanel::DnsRoots::Resolver module) (@INC contains: /usr/local/cpanel /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib /usr/local/cpanel/3rdparty/perl/528/lib/perl5/5.28.0/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/528/lib/perl5/5.28.0 /opt/cpanel/perl5/528/site_lib/x86_64-linux-64int /opt/cpanel/perl5/528/site_lib) at /dev/fd/63 line 9.
BEGIN failed--compilation aborted at /dev/fd/63 line 9.
```

**Comment by cPWilliamL** [comment]
Hi,

Thank you for the report. I am currently working on this in case TECH-846. In 84, we updated our Dns resolver to libunbound. The fix for this will ensure functionality using both the new and old resolver. I'll also be updating the method to ensure the script gracefully fails when the required module is not present, allowing the rest of the functions not relying on a resolver to continue working.

**Comment by cPWilliamL** [comment]
Hi,

This has been corrected in both master and development branches. Both pre84 and 84 resolver methods are now supported. As well, if the rbl_check() subroutine cannot find the required module, this doesn't break the script entirely, other functions will still work.

Thanks,
